version: '3.8'

services:
  # MySQL
  mysql:
    image: mysql:8.0
    container_name: payee_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payee_db
      MYSQL_USER: payee_user
      MYSQL_PASSWORD: payee_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: payee_backend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=payee_db
      - DB_USERNAME=payee_user
      - DB_PASSWORD=payee_pass
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:8000"
    command: ["sh", "-c", "composer install && php artisan key:generate && php artisan migrate --force && php artisan l5-swagger:generate && php artisan serve --host=0.0.0.0 --port=8000"]

  # Angular Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: payee_frontend
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    ports:
      - "4200:4200"
    environment:
      - BACKEND_URL=http://localhost:8000
    command: [ "sh", "-c", "npm install && npm run start -- --host 0.0.0.0 --poll 2000 --watch" ]

volumes:
  mysql_data: